### ISSUE TITLE
Feedback as requested on reddit

### ISSUE THREAD

**Issue by TomasVotruba** [mlebkowski/registry-compiler#3]
Hey, I'll write just point that pop in my head immediately.

Feel free to take what you need and drop the rest.

### Composer

- I'd update dependencies, there is PHPUnit 6 for a while now, Symfony 3.3 on the way etc.
- add min PHP version to composer, very important
- `"minimum-stability": "stable"` is not really needed
- good job with PSR-4 :+1: it's still not spread as it should be even in modern packages

### Installation

https://github.com/mlebkowski/registry-compiler#installation

- missing a bundle and extension, people use it that way, can help
- I recommend not using tagging, since it's config programming and redundant information, see https://www.tomasvotruba.cz/blog/2017/02/12/drop-all-service-tags-in-your-nette-and-symfony-applications/
- better do that collecting in PHP 
- I got lost in the README, what is the simplest example to show your tool? just few lines of code should be there

### Concept

There have been some good news in Symfony 3.3, that made me drop few packages.
You can see them nicely in this PR: https://github.com/Symplify/Symplify/pull/155

And definitely a add Easy Coding Standard: https://github.com/Symplify/EasyCodingStandard
Increases quality of your code without almost no need to study or take care about the code.

That's about it :+1:

**Comment by mlebkowski** [comment]
Thanks for feedback! I’ll try to respond to each issue separately.

First, the composer file:

 * I don’t have experience in creating libraries for a wide variety of users / framework versions / etc, this is why I created a lib that only suits my needs. This is why I target Symfony 2.x, and the PHP version is implicit
 * Do you think specifying a min version (I think it’s `5.4`) is that important? I understand if it were `7.x`, since there are many projects still on `5.x`, but I doubt anyone using `5.3` would find my lib, given it’s vast popularity :D

**Comment by mlebkowski** [comment]
> missing a bundle and extension, people use it that way, can help

I don’t think I understand. Do you mean to add `RegistryCompilerBundle`, so the installation steps are similar to all the other Symfony packages?

**Comment by mlebkowski** [comment]
> I recommend not using tagging, since it's config programming and redundant information, see https://www.tomasvotruba.cz/blog/2017/02/12/drop-all-service-tags-in-your-nette-and-symfony-applications/

I see your point, yet I don’t think it applies here.

 * Services gathered by the lib don’t have to implement a common base class or interface. Tagging would be required in that case. I agree that I could make the `class` option required, since it’s the only use case I can think of, but…
 * Not all services implementing given contract need to be registered, so simply finding every implementations of `Foo` is not sufficient. Symfony `Command` is a very specific Interface / tag, with no other responsibilities, but that’s not always true.
 * Not all services implementing `Foo` need to be registered with the same registry. I.e. one can have generic `EventSubscriberInterface`, but multiple event dispatchers.
 * Tags can have `alias` or `priority` fields (and there’s a separate idea for custom metadata), and this means it’s not just „bare tagging” you describe. They are not always used, but it’s better to keep the usage uniform across all cases.

**Comment by mlebkowski** [comment]
https://gist.github.com/mlebkowski/1a89eb522e83775d340b3d96a8e01f23  — would you consider this as a good example, or even simpler? A few tweaks required either way, since it’s an example showing a different concept, the lib is only by the way there.

**Comment by TomasVotruba** [comment]
I almost forgot about this :) thanks for reply.

## Composer

- I'd go for Symfony 3.0 and PHP 7.0
- In a 7 months there will be Symfony 4, possibly on PHP 7.1, so that might save you some maintenance energy, that you could put somewhere else

## Related to Bundle

Yep, creating a `RegistryCompilerBundle`

## Tagging

In example, it is related to specific class, here:

![image](https://cloud.githubusercontent.com/assets/924196/25807131/0e9de42e-3406-11e7-997a-5b15953708ca.png)

I understand it has added value for some cases. It should be use ONLY in those case. Otherwise it duplicates what is already there.

> Not all services implementing Foo need to be registered with the same registry. I.e. one can have generic EventSubscriberInterface, but multiple event dispatchers.

It is possible to have multiple Applications and Kernels as well :D , but is that a real use case? 
I prefer coding with Pareto 80/20 principal instead of [everything is possible](http://rationallyspeaking.blogspot.cz/2010/03/anything-is-possible-no-not-really.html).

## Example

Too complicated, didn't read. Could you shorten it to 15 lines top?

**Comment by mlebkowski** [comment]
Does it make sense to have two different use cases? The simple one:

```yaml
# gather all foo implementations:
services:
  foo.chain:
    class: ArrayObject
    tags:
      - name: nassau.registry
        class: FooInterface
  foo.bar:
    class: FooImpl
```

And the full one:

```yaml
# gather only selected foo implementations:
services:
  foo.chain:
    class: ArrayObject
    tags:
      - name: nassau.registry
        tag: foo                     # added
        class: FooInterface
  foo.bar:
    class: FooImpl
    tags:
       - name: foo                   # added
```

Not to mention the required library changes to support gathering by class names.

It would solve the „15 lines example” problem. The most common use case, just gather all of the implementations, any order. I will think about it some more. 


Overall, thanks for the feedback. I probably won’t implement most of it, and even if I do it will take me some time, but those are good hints for me to make better libraries.

**Comment by TomasVotruba** [comment]
Simple over comlex! I'd go for first one - since [Symfony 3.3 even simpler](https://www.tomasvotruba.cz/blog/2017/05/07/how-to-refactor-to-new-dependency-injection-features-in-symfony-3-3/):
 
```yaml
# gather all foo implementations:
services:
  ArrayObject:
    tags:
      - name: nassau.registry
        class: FooInterface
  FooImpl: ~
```

> Overall, thanks for the feedback. I probably won’t implement most of it, and even if I do it will take me some time, but those are good hints for me to make better libraries.

Glad to help! It looks really great, if this is your first package. I'd say if you'd do more open-source, you'll be very good at it.

Ping me in PR, if you need any more code-review :+1:

**Comment by TomasVotruba** [comment]
Feel free to close, if you don't need anything else.

Shameless plug, I wrote 2 short posts (8 minutes of reading in total) about PHP open-source. You might find something useful in there as well:

- https://www.tomasvotruba.cz/blog/2016/09/09/how-to-write-open-source-in-php-1-create-a-repository/
- https://www.tomasvotruba.cz/blog/2016/09/16/how-to-write-open-source-in-php-2-enjoy-skeletons/

**Comment by TomasVotruba** [comment]
Cloding
